### ISSUE TITLE
Bring up Teensy

### ISSUE THREAD

**Issue by griswaldbrooks** [kittcar/kitt_electrical#1]
Using the Teensy 3.5 for the car microcontroller:
- [x] Install Teensy driver on PC (required?)
- [x] Power on Teensy with USB
- [x] Solder headers

**Comment by kiran-mohan** [comment]
Soldered headers, installed Arduino IDE and the Teensy package. As soon as the Teensy was powered via US, the default 1 second interval LED blink program started executing. 

Loaded a faster (0.5 second interval) blink program to test that loading code onto the Teensy actually works - and yes, it does work.
